<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Etudiants extends \App\Entity\Etudiants implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'CNE', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'Nom', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'Prenom', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'CIN', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'Tel', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'Date_naiss', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'Adresse', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'id_e', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'niveau'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'CNE', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'Nom', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'Prenom', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'CIN', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'Tel', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'Date_naiss', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'Adresse', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'id_e', '' . "\0" . 'App\\Entity\\Etudiants' . "\0" . 'niveau'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Etudiants $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCNE(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCNE', []);

        return parent::getCNE();
    }

    /**
     * {@inheritDoc}
     */
    public function setCNE(string $CNE): \App\Entity\Etudiants
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCNE', [$CNE]);

        return parent::setCNE($CNE);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $Nom): \App\Entity\Etudiants
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$Nom]);

        return parent::setNom($Nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $Prenom): \App\Entity\Etudiants
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$Prenom]);

        return parent::setPrenom($Prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function getCIN(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCIN', []);

        return parent::getCIN();
    }

    /**
     * {@inheritDoc}
     */
    public function setCIN(string $CIN): \App\Entity\Etudiants
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCIN', [$CIN]);

        return parent::setCIN($CIN);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel(string $Tel): \App\Entity\Etudiants
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$Tel]);

        return parent::setTel($Tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaiss(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaiss', []);

        return parent::getDateNaiss();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaiss(string $Date_naiss): \App\Entity\Etudiants
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaiss', [$Date_naiss]);

        return parent::setDateNaiss($Date_naiss);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $Adresse): \App\Entity\Etudiants
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$Adresse]);

        return parent::setAdresse($Adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdE(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdE', []);

        return parent::getIdE();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdE(int $id_e): \App\Entity\Etudiants
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdE', [$id_e]);

        return parent::setIdE($id_e);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau(): ?\App\Entity\Niveau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau(?\App\Entity\Niveau $niveau): \App\Entity\Etudiants
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$niveau]);

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
