<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGcGcO9y\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGcGcO9y/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGcGcO9y.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGcGcO9y\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGcGcO9y\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GcGcO9y',
    'container.build_id' => '33fd1b8c',
    'container.build_time' => 1578155723,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGcGcO9y');
