<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJzGVGdI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJzGVGdI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJzGVGdI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJzGVGdI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJzGVGdI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JzGVGdI',
    'container.build_id' => '08f7e667',
    'container.build_time' => 1578241466,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJzGVGdI');
