<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerATHYeVi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerATHYeVi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerATHYeVi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerATHYeVi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerATHYeVi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ATHYeVi',
    'container.build_id' => '31675b22',
    'container.build_time' => 1578183968,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerATHYeVi');
